//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagementSystem.Entity
{
    using SupermarketManagementSystem.Model.Expand;
    using System;
    using System.Collections.Generic;
    
    public partial class member:BaseModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Level { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }

        public string NameEx 
        {
            get { return Name; }
            set { Name = value; RaisePropertyChanged(); }
        }
        public string PasswordEx
        {
            get { return Password; }
            set { Password = value; RaisePropertyChanged(); }
        }
    }
}
