//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagementSystem.Entity
{
    using SupermarketManagementSystem.Helper;
    using SupermarketManagementSystem.Model.Expand;
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class product:BaseModel
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public byte[] Image { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<float> Quantity { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }

        //public BitmapImage BitmapImage
        //{
        //    get
        //    {
        //        return ImageHelper.GetBitmapImage(Image);
        //    }
        //}
    }
}
