//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagementSystem.Entity
{
    using SupermarketManagementSystem.Helper;
    using SupermarketManagementSystem.Model;
    using SupermarketManagementSystem.Model.Expand;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Media.Imaging;

    public partial class stock:BaseModel
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Type { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }

        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductName
        {
            get
            {
                return ProductProvider.Current.GetAll().FirstOrDefault(t => t.Id == ProductId).Name;
            }
        }

        /// <summary>
        /// 扩展的属性
        /// </summary>
        public BitmapImage BitmapImage
        {
            get;
            

                //return ImageHelper.GetBitmapImage(ProductProvider.Current.GetAll().FirstOrDefault(t => t.Id == ProductId).Image);
            
        }

        /// <summary>
        /// 扩展的属性
        /// </summary>
        public string Unit
        {
            get
            {

                return ProductProvider.Current.GetAll().FirstOrDefault(t => t.Id == ProductId).Unit;
            }
        }
    }
}

